.TH MAP_NCBI_GTDB_TAXONOMY 1 2026-7月 "" "map_ncbi_gtdb_taxonomy"
.SH NAME
map_ncbi_gtdb_taxonomy \- map_ncbi_gtdb_taxonomy(registry, ncbi.tax, GTDB.tax)
.SH SYNOPSIS
\fImap_ncbi_gtdb_taxonomy(registry, ncbi.tax, GTDB.tax)\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- . 
.PP
.PP
\fBncbi.tax\fB \fR\- . 
.PP
.PP
\fBGTDB.tax\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.map_ncbi_gtdb_taxonomy at map_ncbi_gtdb_taxonomy.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
