.\" man page create by R# package system.
.TH EXPORTS 1 2000-1月 "export_species_sequence" "export_species_sequence"
.SH NAME
export_species_sequence \- 
.SH SYNOPSIS
\fIexport_species_sequence(\fBregistry\fR as <generic> biocad_registry, 
\fBfile\fR as <generic> StreamWriter);\fR
.SH SEE ALSO
exports
.SH FILES
.PP
biocad_registry.dll
.PP
