.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "imports_metatraits" "imports_metatraits"
.SH NAME
imports_metatraits \- 
.SH SYNOPSIS
\fIimports_metatraits(\fBregistry\fR as <generic> biocad_registry, 
\fBmetatraits\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
