.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_chineseName" "imports_chineseName"
.SH NAME
imports_chineseName \- 
.SH SYNOPSIS
\fIimports_chineseName(\fBregistry\fR as <generic> biocad_registry, 
\fBid\fR as any, 
\fBnames\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
