.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "update_kinetics_registry" "update_kinetics_registry"
.SH NAME
update_kinetics_registry \- 
.SH SYNOPSIS
\fIupdate_kinetics_registry(\fBregistry\fR as <generic> biocad_registry);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
